import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProviders from "./provider";
import Script from 'next/script';
import RecoilRootWrapper from '@/recoil/RecoilWrapper'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_KAKAO_APP_JS_KEY}&autoload=false`}
          strategy="beforeInteractive"
        />
      </head>
      <body className={inter.className}>
        <ReactQueryProviders>
          <RecoilRootWrapper>
            <div className="layout">{children}</div>
          </RecoilRootWrapper>
        </ReactQueryProviders>
      </body>
    </html>
  );
}
